### ISSUE TITLE
Changes on Flux v0.26.0

### ISSUE THREAD

**Issue by pjbgf** [weaveworks/flux2-openshift#10]
We are rolling out a few security related changes in flux2 that may impact `flux2-openshift`. 
Here's a summary of them:

- Enable Seccomp by default using new API (requires Kubernetes 1.19).
- Hard-code userId on container images and enable `securityContext.runAsNonRoot`. 
- Drop all capabilities that are not being used.

I will link the PRs here to keep track of progress.

**Comment by chanwit** [comment]
Thank you so much, @pjbgf

**Comment by chanwit** [comment]
Documented by: https://github.com/fluxcd/website/pull/786

**Comment by pjbgf** [comment]
I will close this issue based on the documentation updates. 
Thank you @chanwit for testing and updating the documentation.
